services:
  db:
    container_name: "postgres-dados-upa-rust"
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dados_upa_db
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup-dados-upa.sql:/docker-entrypoint-initdb.d/backup-dados-upa.sql

volumes:
  postgres_data:
