services:
  db:
    container_name: "postgres-forecast-vision"
    image: postgres:16.4
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: forecast-vision-db
      POSTGRES_USER: forecast-vision
      POSTGRES_PASSWORD: forecast-vision-123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup-dados-upa.sql:/docker-entrypoint-initdb.d/backup-dados-upa.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forecast-vision -d forecast-vision-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  ml_api:
    container_name: "ml_models_api"
    build:
      context: ./ml_models_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml_models_api/app:/app/app
    networks:
      - app-network
    restart: always

  rust_app:
    container_name: rust_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://forecast-vision:forecast-vision-123@db:5432/forecast-vision-db
      ML_API_URL: http://ml_api:8000
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      ml_api:
        condition: service_started
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
